name: crypto_coins_list #Назва додатку
description: Cool crypto application #Default: "A new Flutter project." # опис його, якщо збиратись публікувати 
publish_to: 'none' #Сайт де опубліковано пакет чи додаток 
version: 1.0.0+1 #Стандартна версія додатку

environment: #Встановлює те, яку версію Dart використовує наш Flutter проект 
  sdk: '>=3.2.0-131.0.dev <4.0.0' 

dependencies: #Залежності нашого додатку
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.2

dev_dependencies: #Залежності які використовуються Flutter додатком в момент розробки
  flutter_test:
    sdk: flutter 
  flutter_lints: ^2.0.0 #Лінтер не піде в підсумкову зборку і не буде займати зайве місце на гаджеті користувача

flutter: #Тут можна вказати всі додаткові залежності нашого додатку та, якісь конфігураційні налаштування 
  uses-material-design: true 

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
