// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnHlSuOgrACeHzvZoTztMg-2ofB5yN0Eo',
    appId: '1:676274884949:web:b8b23295ad7dde4e18dfdc',
    messagingSenderId: '676274884949',
    projectId: 'crypto-list-app-01',
    authDomain: 'crypto-list-app-01.firebaseapp.com',
    storageBucket: 'crypto-list-app-01.appspot.com',
    measurementId: 'G-Y67ZWQHX9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIX8NPGaHpQwGhGas6TWEnzjbc4Q7mrfQ',
    appId: '1:676274884949:android:93a935a6b5d2338318dfdc',
    messagingSenderId: '676274884949',
    projectId: 'crypto-list-app-01',
    storageBucket: 'crypto-list-app-01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcHOoY_M_nTMigilPRAVYzh6lmF8nauBc',
    appId: '1:676274884949:ios:93897e9d8789b78118dfdc',
    messagingSenderId: '676274884949',
    projectId: 'crypto-list-app-01',
    storageBucket: 'crypto-list-app-01.appspot.com',
    iosBundleId: 'com.cryptoguys.cryptoCoinsList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcHOoY_M_nTMigilPRAVYzh6lmF8nauBc',
    appId: '1:676274884949:ios:f0a22da7b4d223ec18dfdc',
    messagingSenderId: '676274884949',
    projectId: 'crypto-list-app-01',
    storageBucket: 'crypto-list-app-01.appspot.com',
    iosBundleId: 'com.cryptoguys.cryptoCoinsList.RunnerTests',
  );
}
